POLYGON_API_KEY = 'aVEKa_bWKuNWVESpN6l7dNveblyLL_SU'
FINANCIAL_PREP_API_KEY= 'DLipslPX6AakJGEHlM4aja5eRiteV3fT'
MONGO_DB_USER = 'yeonho50'
MONGO_DB_PASS = 'yl923801'
API_KEY = "PKVQS6IQTO4JF66QWYP6"
API_SECRET = "K8yomgGFGBUxTnoOa5sdAiDhQaeoBRzw0hAMjxi2"
BASE_URL = "https://paper-api.alpaca.markets"