POLYGON_API_KEY = 'aVEKa_bWKuNWVESpN6l7dNveblyLL_SU'
FINANCIAL_PREP_API_KEY= 'DLipslPX6AakJGEHlM4aja5eRiteV3fT'
MONGO_DB_USER = 'yeonho50'
MONGO_DB_PASS = 'yl923801'
API_KEY = "ALPACA_API_KEY"
API_SECRET = "ALPACA_SECRET_API_KEY"
BASE_URL = "https://paper-api.alpaca.markets"
